PALETTES = {
    'red_on_grey': {
            0x00: ('grey', ('bold')),   # usually shows as nothing... no dots!
            0x01: ('red', ('bold',) ),
            0x02: ('red', ('bold',) ),
            0x03: ('red', ('bold',) ),
            0x04: ('red', ('bold',) ),
            0x05: ('red', ('bold',) ),
            0x06: ('red', ('bold',) ),
            0x07: ('red', ('bold',) ),
            0x08: ('red', ('bold',) ),
            0x09: ('red', ('bold',) ),
            0x0a: ('red', ('bold',) ),
            0x0b: ('red', ('bold',) ),
            0x0c: ('red', ('bold',) ),
            0x0d: ('red', ('bold',) ),
            0x0e: ('red', ('bold',) ),
            0x0f: ('red', ('bold',) ),
            0x10: ('red', ('bold',) ),
            0x11: ('red', ('bold',) ),
            0x12: ('red', ('bold',) ),
            0x13: ('red', ('bold',) ),
            0x14: ('red', ('bold',) ),
            0x15: ('red', ('bold',) ),
            0x16: ('red', ('bold',) ),
            0x17: ('red', ('bold',) ),
            0x18: ('red', ('bold',) ),
            0x19: ('red', ('bold',) ),
            0x1a: ('red', ('bold',) ),
            0x1b: ('red', ('bold',) ),
            0x1c: ('red', ('bold',) ),
            0x1d: ('red', ('bold',) ),
            0x1e: ('red', ('bold',) ),
            0x1f: ('red', ('bold',) ),
            0x20: ('white', ),
            0x21: ('white', ),
            0x22: ('white', ),
            0x23: ('white', ),
            0x24: ('white', ),
            0x25: ('white', ),
            0x26: ('white', ),
            0x27: ('white', ),
            0x28: ('white', ),
            0x29: ('white', ),
            0x2a: ('white', ),
            0x2b: ('white', ),
            0x2c: ('white', ),
            0x2d: ('white', ),
            0x2e: ('white', ),
            0x2f: ('white', ),
            0x30: ('white', ),
            0x31: ('white', ),
            0x32: ('white', ),
            0x33: ('white', ),
            0x34: ('white', ),
            0x35: ('white', ),
            0x36: ('white', ),
            0x37: ('white', ),
            0x38: ('white', ),
            0x39: ('white', ),
            0x3a: ('white', ),
            0x3b: ('white', ),
            0x3c: ('white', ),
            0x3d: ('white', ),
            0x3e: ('white', ),
            0x3f: ('white', ),
            0x40: ('white', ),
            0x41: ('white', ),
            0x42: ('white', ),
            0x43: ('white', ),
            0x44: ('white', ),
            0x45: ('white', ),
            0x46: ('white', ),
            0x47: ('white', ),
            0x48: ('white', ),
            0x49: ('white', ),
            0x4a: ('white', ),
            0x4b: ('white', ),
            0x4c: ('white', ),
            0x4d: ('white', ),
            0x4e: ('white', ),
            0x4f: ('white', ),
            0x50: ('white', ),
            0x51: ('white', ),
            0x52: ('white', ),
            0x53: ('white', ),
            0x54: ('white', ),
            0x55: ('white', ),
            0x56: ('white', ),
            0x57: ('white', ),
            0x58: ('white', ),
            0x59: ('white', ),
            0x5a: ('white', ),
            0x5b: ('white', ),
            0x5c: ('white', ),
            0x5d: ('white', ),
            0x5e: ('white', ),
            0x5f: ('white', ),
            0x60: ('white', ),
            0x61: ('white', ),
            0x62: ('white', ),
            0x63: ('white', ),
            0x64: ('white', ),
            0x65: ('white', ),
            0x66: ('white', ),
            0x67: ('white', ),
            0x68: ('white', ),
            0x69: ('white', ),
            0x6a: ('white', ),
            0x6b: ('white', ),
            0x6c: ('white', ),
            0x6d: ('white', ),
            0x6e: ('white', ),
            0x6f: ('white', ),
            0x70: ('white', ),
            0x71: ('white', ),
            0x72: ('white', ),
            0x73: ('white', ),
            0x74: ('white', ),
            0x75: ('white', ),
            0x76: ('white', ),
            0x77: ('white', ),
            0x78: ('white', ),
            0x79: ('white', ),
            0x7a: ('white', ),
            0x7b: ('white', ),
            0x7c: ('white', ),
            0x7d: ('white', ),
            0x7e: ('white', ),
            0x7f: ('red', ('bold',)),
            # default color
            None: ('green', ),
        },
    'white_on_grey': {
            #0x00: ('grey', ('bold')),   # usually shows as nothing... no dots!
            #0x01: ('red', ('bold',) ),
            #0x02: ('red', ('bold',) ),
            #0x03: ('red', ('bold',) ),
            #0x04: ('red', ('bold',) ),
            #0x05: ('red', ('bold',) ),
            #0x06: ('red', ('bold',) ),
            #0x07: ('red', ('bold',) ),
            #0x08: ('red', ('bold',) ),
            #0x09: ('red', ('bold',) ),
            #0x0a: ('red', ('bold',) ),
            #0x0b: ('red', ('bold',) ),
            #0x0c: ('red', ('bold',) ),
            #0x0d: ('red', ('bold',) ),
            #0x0e: ('red', ('bold',) ),
            #0x0f: ('red', ('bold',) ),
            #0x10: ('red', ('bold',) ),
            #0x11: ('red', ('bold',) ),
            #0x12: ('red', ('bold',) ),
            #0x13: ('red', ('bold',) ),
            #0x14: ('red', ('bold',) ),
            #0x15: ('red', ('bold',) ),
            #0x16: ('red', ('bold',) ),
            #0x17: ('red', ('bold',) ),
            #0x18: ('red', ('bold',) ),
            #0x19: ('red', ('bold',) ),
            #0x1a: ('red', ('bold',) ),
            #0x1b: ('red', ('bold',) ),
            #0x1c: ('red', ('bold',) ),
            #0x1d: ('red', ('bold',) ),
            #0x1e: ('red', ('bold',) ),
            #0x1f: ('red', ('bold',) ),
            0x20: ('white', ('bold',)),
            0x21: ('white', ('bold',)),
            0x22: ('white', ('bold',)),
            0x23: ('white', ('bold',)),
            0x24: ('white', ('bold',)),
            0x25: ('white', ('bold',)),
            0x26: ('white', ('bold',)),
            0x27: ('white', ('bold',)),
            0x28: ('white', ('bold',)),
            0x29: ('white', ('bold',)),
            0x2a: ('white', ('bold',)),
            0x2b: ('white', ('bold',)),
            0x2c: ('white', ('bold',)),
            0x2d: ('white', ('bold',)),
            0x2e: ('white', ('bold',)),
            0x2f: ('white', ('bold',)),
            0x30: ('white', ('bold',)),
            0x31: ('white', ('bold',)),
            0x32: ('white', ('bold',)),
            0x33: ('white', ('bold',)),
            0x34: ('white', ('bold',)),
            0x35: ('white', ('bold',)),
            0x36: ('white', ('bold',)),
            0x37: ('white', ('bold',)),
            0x38: ('white', ('bold',)),
            0x39: ('white', ('bold',)),
            0x3a: ('white', ('bold',)),
            0x3b: ('white', ('bold',)),
            0x3c: ('white', ('bold',)),
            0x3d: ('white', ('bold',)),
            0x3e: ('white', ('bold',)),
            0x3f: ('white', ('bold',)),
            0x40: ('white', ('bold',)),
            0x41: ('white', ('bold',)),
            0x42: ('white', ('bold',)),
            0x43: ('white', ('bold',)),
            0x44: ('white', ('bold',)),
            0x45: ('white', ('bold',)),
            0x46: ('white', ('bold',)),
            0x47: ('white', ('bold',)),
            0x48: ('white', ('bold',)),
            0x49: ('white', ('bold',)),
            0x4a: ('white', ('bold',)),
            0x4b: ('white', ('bold',)),
            0x4c: ('white', ('bold',)),
            0x4d: ('white', ('bold',)),
            0x4e: ('white', ('bold',)),
            0x4f: ('white', ('bold',)),
            0x50: ('white', ('bold',)),
            0x51: ('white', ('bold',)),
            0x52: ('white', ('bold',)),
            0x53: ('white', ('bold',)),
            0x54: ('white', ('bold',)),
            0x55: ('white', ('bold',)),
            0x56: ('white', ('bold',)),
            0x57: ('white', ('bold',)),
            0x58: ('white', ('bold',)),
            0x59: ('white', ('bold',)),
            0x5a: ('white', ('bold',)),
            0x5b: ('white', ('bold',)),
            0x5c: ('white', ('bold',)),
            0x5d: ('white', ('bold',)),
            0x5e: ('white', ('bold',)),
            0x5f: ('white', ('bold',)),
            0x60: ('white', ('bold',)),
            0x61: ('white', ('bold',)),
            0x62: ('white', ('bold',)),
            0x63: ('white', ('bold',)),
            0x64: ('white', ('bold',)),
            0x65: ('white', ('bold',)),
            0x66: ('white', ('bold',)),
            0x67: ('white', ('bold',)),
            0x68: ('white', ('bold',)),
            0x69: ('white', ('bold',)),
            0x6a: ('white', ('bold',)),
            0x6b: ('white', ('bold',)),
            0x6c: ('white', ('bold',)),
            0x6d: ('white', ('bold',)),
            0x6e: ('white', ('bold',)),
            0x6f: ('white', ('bold',)),
            0x70: ('white', ('bold',)),
            0x71: ('white', ('bold',)),
            0x72: ('white', ('bold',)),
            0x73: ('white', ('bold',)),
            0x74: ('white', ('bold',)),
            0x75: ('white', ('bold',)),
            0x76: ('white', ('bold',)),
            0x77: ('white', ('bold',)),
            0x78: ('white', ('bold',)),
            0x79: ('white', ('bold',)),
            0x7a: ('white', ('bold',)),
            0x7b: ('white', ('bold',)),
            0x7c: ('white', ('bold',)),
            0x7d: ('white', ('bold',)),
            0x7e: ('white', ('bold',)),
            #0x7f: ('red', ('bold',)),
            # default color
            None: ('white', ('bold',) ),
        }
}

